### ISSUE TITLE
Access to Log files

### ISSUE THREAD

**Issue by BananaAcid** [ProjectCeleste/Celeste.Launcher#91]
A button or alike to access the log files.

The latest update mentions "Log files that makes it easier to diagnose problems", but there seems to be no way to access them, nor could I find any info on the location where these files might be.

First, I could launch the launcher, but the game would not start and a popup was telling me to look into the mysterious log files.
Now, the launcher would not start anymore.

**Comment by martinmine** [comment]
These mysterious log-files are located in the mysterious log-folder that is located in the same directory where the launcher executable is running. Since the location of the logs folder is very visible already, and that the logs are meant for technical trouble-shooting, I do not think it is worth having a separate button in the launcher UI that only opens the Logs-folder. It is also not an usual pattern to have a log button that lets you open an application's log directory (or the Windows Event logs).

**Comment by BananaAcid** [comment]
Oh - very mysterious in deed: It mysteriously showed up at the game folder (capital L it has) :) 

Thanks :)
