### ISSUE TITLE
Mysteriously crashing on launcher GUI start

### ISSUE THREAD

**Issue by BananaAcid** [ProjectCeleste/Celeste.Launcher#92]
# What
I worked on first start. Subsequent starts just never shows the GUI anymore.

## What I did

Just executing the `Celeste_Launcher_Gui.exe`.

## Expected behavior

It would be nice, to have it show up.

# Errors

Some Log from the mysterious `Logs` file

```
2020-11-03 00:36:43.624 +01:00 [INF] Preparing to start game, is offline: true
2020-11-03 00:36:43.627 +01:00 [INF] User is online, will perform game scan
2020-11-03 00:36:43.627 +01:00 [INF] Starting quick game scan
2020-11-03 00:36:43.627 +01:00 [INF] Preparing games canner api
2020-11-03 00:36:43.735 +01:00 [INF] Game files passed file scanner
2020-11-03 00:36:43.736 +01:00 [INF] CustomScn directory: D:\Games\steamapps\steamapps\common\Age Of Empires Online\Scenario\CustomScn
2020-11-03 00:36:43.736 +01:00 [INF] Scenario directory: C:\Users\BananaAcid\Documents\Spartan\Scenario
2020-11-03 00:36:43.736 +01:00 [ERR] Das System kann den angegebenen Pfad nicht finden
System.ComponentModel.Win32Exception (0x80004005): Das System kann den angegebenen Pfad nicht finden
   bei Celeste_Public_Api.Helpers.Misc.GetRealPath(String path) in D:\a\1\s\Libs\Celeste_Public_Api\Helpers\Misc.cs:Zeile 176.
   bei Celeste_Launcher_Gui.Services.GameService.<StartGame>d__4.MoveNext() in D:\a\1\s\Celeste_Launcher_Gui\Services\GameService.cs:Zeile 272.
```

-> `ERR: The system could not find the specified path` ... 
-> in that steam folder was a Scenario\CustomScn file (?) with a link icon on it. Clicking it showed a folder does not exist message.

## What I tried

- I removed the `CustomScn` link file, and created a regular folder -> did not work
- I removed my `CustomScn` folder -> did not work

### both resulted in no further error log creation. But the Gui does still not show up.

**Comment by martinmine** [comment]
Can't really help you much since you are not providing much context. (What OS are you on, what version, etc. etc.) You say for example that only by executing the launcher binary, it doesn't appear, while the log you quoted shows that you performed a game scan.

Some steps I would try out based on the information you are providing:
- Delete the path where your game files are and re-run a game-scan
- Delete the `CelesteConfig.xml` file that is in the same directory as `Celeste Launcher.exe`

It also looks like you are starting to launch the old launcher, since the launcher was renamed to `Celeste Launcher.exe` in the last update.

**Comment by BananaAcid** [comment]
Re-Installed my Windows10 and with that AOE-O and Celeste. Everything works now.
