### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by tatsujb** [ProjectCeleste/Celeste.Launcher#93]
# feature

hi there! Linux gamer here!

I see that this project is fully in C# it could be compiled to a linux binary. AOE online runs well for me from steam under ubuntu 20.04 (steam of course runs it via proton)

the launcher itself could be native however, is this something you guys could perhaps do?

thanks a bunch!

**Comment by martinmine** [comment]
Hi, and thanks for showing interest for Linux users!
The launcher is using WPF as the API for building the user interface. This is unfortunately not available on Linux. We would get one step further once we target .NET Core, but as long as Microsoft isn't distributing .NET Core through Windows Update, the players have to install .NET Core before being able to start the launcher. This would provide a worse user-experience for players who are not very experienced installing software on their machines and is therefore something I want to wait with until this is in place before we move from .NET Framework to .NET Core, or .NET 5. But even though we would target .NET Core, WPF still remains to be implemented on Linux, unless you start using something like Wine: https://ccifra.github.io/PortingWPFAppsToLinux/Overview.html

Regarding whether we could write a new native launcher only on Linux, I do not see that happening due to how few players are on Linux and that we much rather want to invest the resources we have on other aspects of the game.

You could also have a look at a command line utility program for the game scanner I put together a while ago, which compiles on Linux: https://github.com/ProjectCeleste/Celeste.GameScan

**Comment by tatsujb** [comment]
makes sense. I myself have .net core installed but I can tell you from experience it's currently a major hassle to do right currently on linux. 

Microsoft is just barely rolling it out for linux and they're basically gonna skip straight to version 5 and ignore the previous versions I think.

**Comment by martinmine** [comment]
Idk why you are having issues with .NET Core, but I know _a lot_ of companies are running it without issues in a production environment pretty successfully, also been using myself on Arch, Fedora, and CentOS without any issues. Out of curiosity, what kind of issues are you having and on what Linux distro are you on?

The game scanner does the same as when you perform a game scan with the launcher. It patches the game files with modifications that we in the Celeste dev team have pushed out.

**Comment by tatsujb** [comment]
ok.

I'm not sure that I have issues but installing it, I found and tried many different methods. In the end I was unsure I actually had a full core 5.0 stack or some incomplete or dysfunctional setup. 

it's really not your usual "sudo apt install program" the way it should be.

It probably got better just recently.
