### ISSUE TITLE
Launcher Doesn't Start

### ISSUE THREAD

**Issue by TheDood1092** [ProjectCeleste/Celeste.Launcher#98]
I click celeste launcher.exe and nothing happens.

I've done a clean install of the game, installed the launcher from the website and followed all instructions. When I double-click the launcher, it briefly appears in task manager and then quickly disappears.

**Comment by martinmine** [comment]
Sounds like the launcher crashes. Check in the Logs folder if you find a launcherlog<todaysdate>.log, it should contain an exception if it crashed, that would make it possible to figure out what is going on.

**Comment by TheDood1092** [comment]
Hi! Thanks for replying so quickly :)

Here is the content of the launcherlog:

2022-04-11 21:25:25.700 +00:00 [INF] Initializing bootstrapper
2022-04-11 21:25:25.771 +00:00 [INF] No user config loaded, path C:\Program Files (x86)\Age Of Empires Online\CelesteConfig.xml does not exist
2022-04-11 21:25:25.775 +00:00 [INF] Game path set to C:\Program Files (x86)\Age Of Empires Online\CelesteConfig.xml
2022-04-11 21:25:25.776 +00:00 [INF] IsSteamVersion: false
2022-04-11 21:25:25.781 +00:00 [INF] Initialized web socket
2022-04-11 21:25:25.781 +00:00 [INF] Initializing fingerprint provider
2022-04-11 21:25:25.791 +00:00 [INF] Localized UI language to English (United States)
2022-04-11 21:25:25.792 +00:00 [INF] Bootstrapper initialized

**Comment by TheDood1092** [comment]
Also I try to run using Spartan.exe and a dialogue tells me to run the game from the launcher. I've not been able to get this running on windows 7 or 10. I've even tried Linux with no luck. I ran the game on all these systems years ago, perhaps my account got purged? Still, I need the launcher to create a new one.

**Comment by martinmine** [comment]
You have the launcher placed in `C:\Program Files (x86)\Age Of Empires Online\` ? If so, move the launcher somewhere else (make for example a Celeste folder in your Documents folder or wherever you might desire) and move it there. I suspect your launcher is crashing due to insufficient rights being in the program files directory.

**Comment by TheDood1092** [comment]
I've tried running from Downloads folder. It's doing the same thing.

**Comment by martinmine** [comment]
Open event viewer (right click start button and select event viewer), look under Windows Logs/Application, do you see any error events there?

**Comment by TheDood1092** [comment]
I have one of those 'Light' versions of windows, it doesn't have firewall, event viewer or add/remove features. I've been using it for years without an issue but with this modern .net framework stuff I'm starting to think that it could be the issue. I'll go install full Windows 10. Sorry to waste your time. Have a good one.

**Comment by martinmine** [comment]
Out of curiosity, which version of Windows are you using? Would be helpful for others to know in case they would encounter a similar issue.

**Comment by TheDood1092** [comment]
Windows 10: MPB Gamer Elegant Edition (TC&AXE Build - Made Under TeamOS Forum Support) Cheers!

**Comment by martinmine** [comment]
I would highly recommend you to use a Windows version that Microsoft published and not some bootleg edit some guys put together on the net. It makes it hard to stay up to date with security patches, and then you have some edge cases where they thought it would be a good idea to strip out some modules of the OS and then you run into problems like these. I suspect in this case they either removed all of .NET Framework or parts of it. In Windows, that is an essential part of the OS and I (as a developer) have an expectation that all versions of Windows is going to support .NET Framework because that is how things are. If you feel Windows 10 is too bloated I would suggest you to have a look at Windows 10 LTSB but there are lots of people arguing you shouldn't even use that because of other reasons. I wish you best of luck!
